name: PR Checks

on:
    pull_request:
        branches:
            - main

jobs:
    biome-front:
        name: Biome Checks - Frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              working-directory: ./front
              run: bun install

            - name: Run Biome check
              working-directory: ./front
              run: bun run check

    tests-api:
        name: Tests - Backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              working-directory: ./api
              run: bun install

            - name: Generate Prisma Client
              working-directory: ./api
              run: bun run db:generate

            - name: Run tests
              working-directory: ./api
              run: bun test
